# Site settings
title: Michael Tran
description: Portfolio page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Tran
user_description: Hi.
user_title: Software Engineering and Commerce Student
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  mqtran01
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
